apiVersion: v1
kind: Namespace
metadata:
  name: privchats-system
  labels:
    app: privchats
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: privchats-nginx-config-map
  namespace: privchats-system
data:
  nginx.conf: |    
    user root;
    worker_processes auto;
    error_log /var/log/nginx/error.log;
    pid /run/nginx.pid;

    include /usr/share/nginx/modules/*.conf;

    events {
        worker_connections 1024;
    }

    http {
        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';
                          
    server {
        listen         80;
        server_name    privchats.com;
        return         301 www.$server_name$request_uri;
    }
    

    server {
        listen         80;
        server_name    www.privchats.com;

        location /static {
            alias /static/;     
        }

        location /media {
            alias /media/;     
            client_max_body_size 200M;
        }    

        location / {
            proxy_pass http://localhost:8000;
            proxy_set_header Host $host;
            proxy_http_version 1.1;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            client_body_temp_path /tmp/nginx 1 2;
            client_max_body_size 200M;
        }    
    }
        access_log  /var/log/nginx/access.log  main;

        sendfile            on;
        tcp_nopush          on;
        tcp_nodelay         on;
        keepalive_timeout   65;
        types_hash_max_size 2048;

        include             /etc/nginx/mime.types;
        default_type        application/octet-stream;
    }    
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: privchats
  namespace: privchats-system
  labels:
    app: privchats
spec:
  replicas: 1
  selector:
    matchLabels:
      app: privchats
  template:
    metadata:
      labels:
        app: privchats
    spec:
      imagePullSecrets:
      - name: myregistrykey
      volumes:
        - name: privchats-nginx-config
          configMap:
            name: privchats-nginx-config-map
        - name: static
          emptyDir: {}
      containers:
      - name: nginx
        image: nginx:latest        
        ports:
        - containerPort: 80
        volumeMounts:
        - name: privchats-nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        - name: static
          mountPath: /static
      - name: redis
        image: redis:alpine
        ports:
        - containerPort: 6379
      - name: privchats
        image: mmoxam/inringame:privchats-latest
        imagePullPolicy: Always
        env:
        - name: isKubernetes
          value: "True"    
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: static
          mountPath: /static
        lifecycle:
          postStart:
            exec:
              command: ["cp", "-a", "/app/static/.", "/static/"]
---

apiVersion: v1
kind: Service
metadata:
  name: privchats-svc
  namespace: privchats-system
  annotations:
    traefik.ingress.kubernetes.io/affinity: "true"
spec:
  selector:
    app: privchats
  ports:
  - name: web
    port: 80
    targetPort: 80
---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: privchats-ingress
  namespace: privchats-system
  annotations:
    kubernetes.io/ingress.class: "traefik"
    traefik.ingress.kubernetes.io/preserve-host: "true"
    ingress.kubernetes.io/ssl-redirect: "true"
    certmanager.k8s.io/cluster-issuer: "letsencrypt-prod"
    certmanager.k8s.io/acme-challenge-type: http01
spec:
  rules:
  - host: privchats.com
    http:
      paths:
      - path: /
        backend:
          serviceName: privchats-svc
          servicePort: 80
  - host: www.privchats.com
    http:
      paths:
      - path: /
        backend:
          serviceName: privchats-svc
          servicePort: 80
  tls:
    - secretName: privchats-tls-cert
      hosts:
        - privchats.com
        - www.privchats.com
